#test:
#  stage: test
#  only:
#    - develop
#    - release/staging
#  script:
#    - npm install
#    - npm test

# deploy:
#   stage: deploy
#   only:
#     - demo
#  script:
#    - chmod 600 .deploy/prep_staging_key_pair.pem
#    - apk update && apk upgrade
#    - apk add git openssh bash
#    - pm2 deploy ecosystem.json production update
